# Generated by Django 3.0.2 on 2020-02-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='post',
        ),
    ]
